### PR TITLE
Add CyberConnect and LIT filters

### PR DESCRIPTION
**Pull request by NftTopBest**
* Gate messages with CyberConnect and LIT
  * User can filter by CyberConnect Social Data: friends, followings, followers
  * User can pick the `all` filter that means all the conversations will show up event they do not include in the CyberConnect Social Data
  * User can add LIT control filter too
    * User can select which chain to query for the conditions below
    * User can add ETH, ERC20, ERC721, ERC777, ERC1155 token filters with contract address, comparators (<,<=, =, >=, >), and number
    * All of conditions can be `Intersection` or `Union`
    * User hit the `Calculate with LIT` button will trigger query with LIT and also show the calculate result for each condition and the final result
    * The calculate result will be `intersection` with the CyberConnect Social Data
* In the messages list, user can click on the avatar to go to the [W3NS](https://web3nft.social/0xC6E58fb4aFFB6aB8A392b7CC23CD3feF74517F6C) home page to check the user's more detail social informations
  * User can follow / unfollow some one on W3NS home page
  * User can check someone's followers / followings (something like Instagram)
  * User can click on the `Chat` button to jump to the XMTP application to chat with the user

### CODE REVIEW

**Comment by petermdenton** [comment]
@NftTopBest - it looks you accidentally did a PR against our example-chat-app. Could you fork the chat app, then do a PR against your fork and then submit to Gitcoin?

**Comment by NftTopBest** [comment]
> @NftTopBest - it looks you accidentally did a PR against our example-chat-app. Could you fork the chat app, then do a PR against your fork and then submit to Gitcoin?

ok. working on it.

**Comment by saulmc** [comment]
Thanks @NftTopBest! We'll close out this PR and look forward to seeing your fork.

**Comment by NftTopBest** [comment]
> 
Hi @petermdenton, here it is.

PR here: https://github.com/NftTopBest/example-chat-react-gitcoin-hackathon/pull/1

I deploy it on https://chat.web3nft.social/
And also from  https://dev.web3nft.social/0xC6E58fb4aFFB6aB8A392b7CC23CD3feF74517F6C, we can follow/unfollow someone, then click on the chat button to go to the XMTP chat system.

Also in the XMTP chat system, users can click on the avatar to link back to the dev.web3nft.social page ;)

 [Video demo for Main Application and Chat Application](https://www.loom.com/share/f49d8e0c76d14e8eb8390804026b1a3b)
 
Also here are some of the screenshots I saved before.
https://github.com/NftTopBest/web3nft.social/tree/main/screenshot


Full hackathon information: https://github.com/NftTopBest/web3nft.social

**Pull request closed without merging**
