### PR TITLE
Upgrade SDK to 6.0.0

### PR DESCRIPTION
**Pull request by neekolas**
## Summary
- Upgrades SDK to 6.0.0
- Adds support for local environment, and for setting the environment from env vars

## Testing Guide
1. Go into `xmtp-js` repo on the `message-grpc-client-integration` branch
2. `npm i && npm link`
3. Go back to this repo (on the `grpc-api` branch)
4. `npm link @xmtp/xmtp-js`
5. `npm run dev`
6. (bonus points) set `NEXT_PUBLIC_XMTP_ENVIRONMENT=local` and spin up a local Docker node from `xmtp-js` to run with  auth token validation turned on

## Acceptance criteria
- Can sign in with new Ethereum wallet
- Can sign in with existing Ethereum wallet, and only be prompted once
- Can view message history
- Can send message (and confirm receipt on the other end)
- Can receive streaming messages in real-time

### CODE REVIEW

**Comment by mkobetic** [comment]
I'm failing on step 4.
```
example-chat-react % npm link @xmtp/xtmp-js
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@xmtp%2fxtmp-js - Not found
npm ERR! 404
npm ERR! 404  '@xmtp/xtmp-js@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/martin/.npm/_logs/2022-08-17T20_20_18_532Z-debug.log
```

**Comment by jazzz** [comment]
On fresh clone, Steps 1-5 work for me. App loads, I can login, and send messages

**Comment by neekolas** [comment]
@mkobetic Not sure why that would happen. Do you have any other packages NPM linked? You can find out by running `npm ls -g --depth=0 --link=true`

**Comment by neekolas** [comment]
@mkobetic wait. Now I see it. You have `xtmp` instead of `xmtp`

**Comment by mkobetic** [comment]
> @mkobetic wait. Now I see it. You have `xtmp` instead of `xmtp`

Oops, sorry.

**Comment by mkobetic** [comment]
Gotta wrap up, didn't manage the bonus yet, but the basics seems to work 🥳

**Comment by mkobetic** [comment]
Tested out the authentication setup too, seems to work fine. :shipit:

**Comment by neekolas** [comment]
Thanks for the help @jazzz @mkobetic. I'm gonna ship it after my next meeting

**Review by mkobetic — APPROVED** [review]
🥳

**Pull request merged**
